# Generated by Django 4.0.5 on 2022-06-08 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_teachercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachercourse',
            old_name='teahcer',
            new_name='teacher',
        ),
    ]
