# Generated by Django 4.0.5 on 2022-06-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
