# Generated by Django 4.0.5 on 2022-06-04 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=15)),
                ('avatar', models.FileField(upload_to='files/avatar')),
                ('phone_number', models.CharField(max_length=15)),
                ('money', models.DecimalField(decimal_places=2, default=500, max_digits=20)),
                ('major', models.CharField(max_length=50)),
                ('UEY', models.IntegerField()),
                ('interests', models.CharField(max_length=150)),
                ('futur_course', models.CharField(max_length=150)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
