# Generated by Django 4.0.5 on 2022-06-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_uey_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UEY',
            field=models.IntegerField(),
        ),
    ]
